"""Benchmark split metadata for each Nr3D row an evaluator may score.

The split tables are generated by ``scripts/prepare/build_benchmark.py`` and
contain the easy/hard and view-dependent/view-independent classifications used
during evaluation.

There is ONE TABLE PER SPLIT, and each is keyed by the row index that split's
parses carry -- the test table by the row's position in ``nr3d_test.csv``, the
dev table by its position in ``nr3d_train.csv``. The keys therefore overlap
numerically between tables while meaning different rows, which is why a table is
chosen by split and never shared: reading dev row 486 out of the test table
returns a real entry for an unrelated utterance.
"""

from __future__ import annotations

import ast
import csv
import json
from collections import Counter
from collections.abc import Iterable
from functools import lru_cache
from pathlib import Path

from grounding.data.benchmark import BOXES_DIR, load_boxes
from grounding.paths import CORPORA, RAW, SPLITS_PATH
from grounding.paths import SPLITS_DEV_PATH as SPLITS_DEV_PATH


# Nr3D test annotations used to construct the split metadata.
ANNO_PATH = RAW / "nr3d_test.csv"

# The dev draw, and the csv its row indices point into. The draw is a subset of
# train rows, so its flags cannot be read off a file of its own rows in order --
# the index has to be carried over from the csv it was drawn from.
DEV_PATH = CORPORA / "nr3d_dev.jsonl"
DEV_ANNO_PATH = CORPORA / "nr3d_train.csv"

VIEW_DEPENDENT_TOKENS = {
    "front",
    "behind",
    "back",
    "right",
    "left",
    "facing",
    "leftmost",
    "rightmost",
    "looking",
    "across",
}


def _tokens(raw: str) -> list[str]:
    """Parse the serialized token list from the annotation CSV."""
    try:
        value = ast.literal_eval(raw)
    except (ValueError, SyntaxError):
        return []

    if not isinstance(value, (list, tuple)):
        return []

    return [str(token) for token in value]


def is_view_dependent(tokens: list[str]) -> bool:
    """Return whether an expression contains a view-dependent token."""
    return any(token in VIEW_DEPENDENT_TOKENS for token in tokens)


def build_rows(
    rows: Iterable[tuple[int, dict]],
    boxes_dir: Path = BOXES_DIR,
) -> dict[str, dict]:
    """Build split metadata for ``(row index, annotation row)`` pairs.

    The index is supplied rather than counted, so a table for a SUBSET of a csv
    keeps that csv's indices -- the ones the subset's parses carry.
    """

    label_counts: dict[str, Counter[str]] = {}

    def counts_for(scan_id: str) -> Counter[str]:
        if scan_id not in label_counts:
            try:
                objects = load_boxes(scan_id, boxes_dir)
            except FileNotFoundError:
                objects = []

            label_counts[scan_id] = Counter(
                obj["label"] for obj in objects
            )

        return label_counts[scan_id]

    out: dict[str, dict] = {}

    for idx, row in rows:
        scan_id = row["scan_id"]
        target_label = row["instance_type"]

        counts = counts_for(scan_id)
        n_same_class = counts[target_label]

        box_path = Path(boxes_dir) / f"{scan_id}_bboxes.json"

        out[str(idx)] = {
            "dataset_idx": idx,
            "scan_id": scan_id,
            "target_id": int(row["target_id"]),
            "target_label": target_label,
            "is_view_dependent": is_view_dependent(
                _tokens(row["tokens"])
            ),
            "is_hard": n_same_class > 2,
            "is_multiple": n_same_class > 1,
            "has_boxes": box_path.is_file(),
        }

    return out


def build(
    anno_path: Path = ANNO_PATH,
    boxes_dir: Path = BOXES_DIR,
) -> dict[str, dict]:
    """Build split metadata for all rows in the Nr3D test annotations."""
    with Path(anno_path).open(newline="") as f:
        return build_rows(enumerate(csv.DictReader(f)), boxes_dir)


def build_dev(
    dev_path: Path = DEV_PATH,
    anno_path: Path = DEV_ANNO_PATH,
    boxes_dir: Path = BOXES_DIR,
) -> dict[str, dict]:
    """Build split metadata for the dev draw, keyed as its parses are.

    ``dataset_idx`` in the dev corpus IS the row's index in ``nr3d_train.csv``,
    and that is what the dev parses carry, so the table is keyed by it. Rows are
    matched on scan and utterance rather than trusted, since a rebuilt train csv
    would shift every index.
    """
    with Path(anno_path).open(newline="") as f:
        anno = list(csv.DictReader(f))

    pairs = []
    for line in Path(dev_path).read_text().splitlines():
        if not line.strip():
            continue
        item = json.loads(line)
        idx = item["dataset_idx"]
        row = anno[idx]
        if (row["scan_id"] != item["scan_id"]
                or row["utterance"].strip() != item["utterance"]):
            raise ValueError(
                f"dev row {idx} does not match {anno_path}: the dev draw "
                "indexes that csv by position; rebuild the draw")
        pairs.append((idx, row))

    return build_rows(pairs, boxes_dir)


@lru_cache(maxsize=4)
def load_splits(path: Path = SPLITS_PATH) -> dict[str, dict]:
    """Load the generated benchmark split metadata."""
    return json.loads(Path(path).read_text())
